openapi: 3.0.1
info:
  title: Strava GPT Plugin
  description: Plugin to access recent Strava workouts
  version: 1.0.0
servers:
  - url: https://strava-gpt-one.vercel.app
paths:
  /api/activities:
    get:
      operationId: getActivities
      summary: Get the user's recent Strava activities
      responses:
        '200':
          description: A list of recent Strava activities
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    distance:
                      type: number
                    moving_time:
                      type: integer
                    type:
                      type: string
                    start_date:
                      type: string
                      format: date-time
